Payroll::CreateNext
jurgens/payroll pull request #14
Opened 2016-10-07 12:14 UTC by roman-yarovoy

2016-10-07 12:16 UTC, roman-yarovoy commented
Тупил из-за возможности изменения дат, так что заняло полтора часа.

2016-10-10 17:15 UTC, jurgens requested changes

2016-10-10 17:15 UTC, jurgens commented on db/seeds.rb
> +Payroll.create!(
интересно, а почему первый payroll создается в сидах? он должен создаваться точно так же как остальные, по запросы пользователя

2016-10-10 17:15 UTC, jurgens commented on db/seeds.rb
> +)
нужна пустая строка

2016-10-10 17:15 UTC, jurgens commented on lib/payroll/create_next.rb
> +  def initialize(first_day: 5, second_day: 20)
негибко - а что если будет выплата не два раза в месяц, а один или три?

2016-10-10 17:15 UTC, jurgens commented on spec/lib/payroll/create_next_spec.rb
> +    Payroll.create!(
опять же, почему ты решил что первый пейролл должен уже быть?

2016-10-11 18:43 UTC, roman-yarovoy commented
@jurgens, поправил. Заняло полтора часа.

2016-10-14 11:13 UTC, closed without merging